### PR TITLE
Fix/provider data type dynamic

### PR DESCRIPTION
**Pull request by Defuera**
Fixes for purchase flow models
- Change providerData type to dynamic
- Make `OrderInfo` fields nullable as by documentation https://core.telegram.org/bots/api#orderinfo

### CODE REVIEW

**Comment by HeySreelal** [comment]
Thanks for the improvements, @Defuera!

**Comment by Defuera** [comment]
@HeySreelal would you release this for me? :)

**Comment by HeySreelal** [comment]
Will surely do that!

**Comment by HeySreelal** [comment]
Once second, why do we need the type of `providerData` to be `dynamic`?

**Comment by HeySreelal** [comment]
Hey @Defuera, are we still on this? Please let me know this :)

> Once second, why do we need the type of `providerData` to be `dynamic`?

**Pull request merged**
