### PR TITLE
Optionally enable logging

### PR DESCRIPTION
**Pull request by devsdocs**
Additionally to DioException, to help debugging case like [this](https://github.com/HeySreelal/televerse/issues/143)
Set to false by default.

### CODE REVIEW

**Comment by HeySreelal** [comment]
Perfect, looks good to me. 

Btw, have you tested this?

**Comment by devsdocs** [comment]
Already test it, works good.

**Comment by HeySreelal** [comment]
Awesome! Thanks for raising this! 🚀

**Comment by HeySreelal** [comment]
Just tested it myself, do we really need to log the recurring `getUpdates` calls?

**Comment by devsdocs** [comment]
Just updated the code please check

**Comment by HeySreelal** [comment]
Cool! I'm good to go with this. 

Btw, just asking - wouldn't it be really great if the user could attach loggers to specific method calls? Do you have any ideas on this?

**Comment by devsdocs** [comment]
Well, one way to do it, add optional bool params for methods, that always override global log flag

**Comment by HeySreelal** [comment]
Thanks!! I've updated the `dev` branch in another way. Can you check if it's working and looks good?

Basically, I've listed all the methods as a new enum. Now the `Televerse` class accepts a `LoggerOptions` instance instead of `enableLogging` flag. The `LoggerOptions` accepts a field `methods` where users can list all the methods they wanted logs about.

Please let me know if this works.

CC: @GiuseppeFn @iamcosmin

**Comment by devsdocs** [comment]
Looks good to me

**Pull request merged**
